[package]
name = "cliprs-daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
cliprs-ipc = { path = "../cliprs-ipc" }
ash = { git = "https://github.com/ash-rs/ash", rev = "f4c2ca3e4f6b998d5254ad101a32f024d87cdec2", features = ["linked"] }
drm = "0.15.0"
drm-fourcc = "2.2.0"
evdev = "0.13.2"
image = "0.25.10"
uuid = { version = "1.27.0", features = ["v4"] }
env_logger = "0.11.11"
log = "0.4.34"
webm-iterable = "0.7.1"
